// <auto-generated />
using System;
using CrmCorner.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CrmCorner.Migrations
{
    [DbContext(typeof(CrmCornerContext))]
    [Migration("20251024114630_AddPersonalUserToPersonalBranding")]
    partial class AddPersonalUserToPersonalBranding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_unicode_ci")
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");

            modelBuilder.Entity("CrmCorner.Models.ApolloContactDbModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CompanyName")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext");

                    b.Property<string>("Headline")
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.Property<string>("LinkedinUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Location")
                        .HasColumnType("longtext");

                    b.Property<string>("PersonId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext");

                    b.Property<string>("SourceLabelId")
                        .HasColumnType("longtext");

                    b.Property<string>("SourceLabelName")
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ApolloContacts");
                });

            modelBuilder.Entity("CrmCorner.Models.ApolloSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ApolloApiToken")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ApolloSettings");
                });

            modelBuilder.Entity("CrmCorner.Models.AppRole", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("CrmCorner.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("City")
                        .HasColumnType("longtext");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("EmailDomain")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("EmployeeCount")
                        .HasColumnType("int");

                    b.Property<byte?>("Gender")
                        .HasColumnType("tinyint unsigned");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NameSurname")
                        .HasColumnType("longtext");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Picture")
                        .HasColumnType("longtext");

                    b.Property<string>("PositionName")
                        .HasColumnType("longtext");

                    b.Property<string>("Sector")
                        .HasColumnType("longtext");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("CrmCorner.Models.AppUserRole", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("appuserrole", (string)null);
                });

            modelBuilder.Entity("CrmCorner.Models.BigecSayfaDeneme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("BigeçSayfaDenemes");
                });

            modelBuilder.Entity("CrmCorner.Models.Calendar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    b.Property<string>("AppUserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Email")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("EndDate")
                        .HasMaxLength(50)
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Guid")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("StartDate")
                        .HasMaxLength(50)
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int?>("ToId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("longtext");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex("AppUserId");

                    b.HasIndex(new[] { "Id" }, "Id");

                    b.ToTable("Calendar", (string)null);
                });

            modelBuilder.Entity("CrmCorner.Models.ChatHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("IsRead")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("MessageTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ReceiverId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SenderId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ChatHistories");
                });

            modelBuilder.Entity("CrmCorner.Models.Company", b =>
                {
                    b.Property<int>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EmailDomain")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool?>("IsApproved")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("CompanyId");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("CrmCorner.Models.CustomerN", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AppUserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CompanyEmail")
                        .HasColumnType("longtext");

                    b.Property<string>("CompanyName")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CustomerEmail")
                        .HasColumnType("longtext");

                    b.Property<string>("CustomerTitle")
                        .HasColumnType("longtext");

                    b.Property<int?>("EmployeeCount")
                        .HasColumnType("int");

                    b.Property<int?>("Industry")
                        .HasColumnType("int");

                    b.Property<string>("LinkedinUrl")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("Source")
                        .HasColumnType("longtext");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.ToTable("CustomerNs");
                });

            modelBuilder.Entity("CrmCorner.Models.EmailList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AppUserId")
                        .HasColumnType("longtext");

                    b.Property<string>("Body")
                        .HasColumnType("longtext");

                    b.Property<string>("CC")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("From")
                        .HasColumnType("longtext");

                    b.Property<bool?>("IsStar")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SendMail")
                        .HasColumnType("longtext");

                    b.Property<string>("Subject")
                        .HasColumnType("longtext");

                    b.Property<string>("To")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("EmailList");
                });

            modelBuilder.Entity("CrmCorner.Models.Feedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("SocialMediaContentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SocialMediaContentId");

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("CrmCorner.Models.FileAttachment", b =>
                {
                    b.Property<int>("FileAttachmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("FileAttachmentId");

                    b.HasIndex("TaskId");

                    b.ToTable("FileAttachments");
                });

            modelBuilder.Entity("CrmCorner.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AppUserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("TaskCompId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("TaskCompId")
                        .IsUnique();

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("CrmCorner.Models.PersonalBrandingContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("EstimatedPublishDate")
                        .HasColumnType("datetime(6)");

                    b.Property<byte[]>("MediaFile")
                        .HasColumnType("longblob");

                    b.Property<string>("PersonalUserId")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("PersonalUserId");

                    b.ToTable("PersonalBrandingContents");
                });

            modelBuilder.Entity("CrmCorner.Models.PersonalBrandingFeedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CreatedById")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("PersonalBrandingContentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("PersonalBrandingContentId");

                    b.ToTable("PersonalBrandingFeedbacks");
                });

            modelBuilder.Entity("CrmCorner.Models.PipelineTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AppUserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool?>("ContactedViaColdCall")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("ContactedViaLinkedIn")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Currency")
                        .HasColumnType("longtext");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CustomerSurname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ExpectedCloseDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LinkedinUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("NegativeReason")
                        .HasColumnType("longtext");

                    b.Property<int?>("OutcomeStatus")
                        .HasColumnType("int");

                    b.Property<int?>("Outcomes")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext");

                    b.Property<string>("ResponsibleUserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Source")
                        .HasColumnType("longtext");

                    b.Property<int>("SourceChannel")
                        .HasColumnType("int");

                    b.Property<int>("Stage")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal?>("Value")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ResponsibleUserId");

                    b.ToTable("PipelineTasks");
                });

            modelBuilder.Entity("CrmCorner.Models.PipelineTaskFileAttachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PipelineTaskId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("PipelineTaskId");

                    b.ToTable("PipelineTaskFileAttachments");
                });

            modelBuilder.Entity("CrmCorner.Models.PipelineTaskHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ChangedField")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NewValue")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OldValue")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PipelineTaskId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PipelineTaskId");

                    b.ToTable("PipelineTaskHistories");
                });

            modelBuilder.Entity("CrmCorner.Models.PipelineTaskLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("NewValue")
                        .HasColumnType("longtext");

                    b.Property<string>("OldValue")
                        .HasColumnType("longtext");

                    b.Property<int?>("PipelineTaskId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedById")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("UpdatedField")
                        .HasColumnType("longtext");

                    b.HasKey("LogId");

                    b.HasIndex("PipelineTaskId");

                    b.HasIndex("UpdatedById");

                    b.ToTable("PipelineTaskLogs");
                });

            modelBuilder.Entity("CrmCorner.Models.PipelineTaskNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Note")
                        .HasColumnType("longtext");

                    b.Property<int>("PipelineTaskId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PipelineTaskId");

                    b.ToTable("PipelineTaskNotes");
                });

            modelBuilder.Entity("CrmCorner.Models.PostSaleInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("CanUseLogo")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsContinuationConsidered")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsFirstPaymentMade")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsThereAProblem")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsTrustpilotReviewed")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("PipelineTaskId")
                        .HasColumnType("int");

                    b.Property<string>("ProblemDescription")
                        .HasColumnType("longtext");

                    b.Property<string>("TrustPilotComment")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("PipelineTaskId")
                        .IsUnique();

                    b.ToTable("PostSaleInfos");
                });

            modelBuilder.Entity("CrmCorner.Models.SocialMediaContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int>("ContentType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<byte[]>("MediaFile")
                        .HasColumnType("longblob");

                    b.Property<DateTime?>("ScheduledPublishDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("SocialMediaContents");
                });

            modelBuilder.Entity("CrmCorner.Models.Status", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("StatusId");

                    b.ToTable("Statuses");
                });

            modelBuilder.Entity("CrmCorner.Models.TableHeader", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ColumnKey")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ColumnName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("TableHeaders");
                });

            modelBuilder.Entity("CrmCorner.Models.TaskComp", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AssignedUserId")
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<int?>("CreatedByCompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("FinalSalesDone")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("HeardFrom")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsFinalDecisionMaker")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NegativeReason")
                        .HasColumnType("longtext");

                    b.Property<int?>("OutcomeStatus")
                        .HasColumnType("int");

                    b.Property<int>("Outcomes")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SalesDone")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SelectedCurrency")
                        .HasColumnType("longtext");

                    b.Property<int?>("StatusId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<decimal?>("ValueOrOffer")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("TaskId");

                    b.HasIndex("AssignedUserId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("StatusId");

                    b.HasIndex("UserId");

                    b.ToTable("TaskComps");
                });

            modelBuilder.Entity("CrmCorner.Models.TaskCompLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("NewValue")
                        .HasColumnType("longtext");

                    b.Property<string>("OldValue")
                        .HasColumnType("longtext");

                    b.Property<int?>("TaskId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedById")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("UpdatedField")
                        .HasColumnType("longtext");

                    b.HasKey("LogId");

                    b.HasIndex("TaskId");

                    b.HasIndex("UpdatedById");

                    b.ToTable("TaskCompLogs");
                });

            modelBuilder.Entity("CrmCorner.Models.TaskCompNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TaskCompId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TaskCompId");

                    b.ToTable("TaskCompNotes");
                });

            modelBuilder.Entity("CrmCorner.Models.ToDo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AppUserId")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DoneList")
                        .HasColumnType("longtext");

                    b.Property<string>("MainGoalTitle")
                        .HasColumnType("longtext");

                    b.Property<string>("NotDoneList")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("SystemDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Title")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdateSystemDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserId")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.ToTable("ToDos");
                });

            modelBuilder.Entity("CrmCorner.Models.ToDoList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DoneList")
                        .HasColumnType("longtext");

                    b.Property<string>("MainGoalTitle")
                        .HasColumnType("longtext");

                    b.Property<string>("NotDoneList")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("SystemDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Title")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdateSystemDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserId")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ToDoList");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("roleclaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("userclaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("userlogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("usertokens", (string)null);
                });

            modelBuilder.Entity("CrmCorner.Models.AppUserRole", b =>
                {
                    b.HasOne("CrmCorner.Models.AppRole", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CrmCorner.Models.AppUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CrmCorner.Models.Calendar", b =>
                {
                    b.HasOne("CrmCorner.Models.AppUser", "AppUser")
                        .WithMany("Calendars")
                        .HasForeignKey("AppUserId");

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("CrmCorner.Models.CustomerN", b =>
                {
                    b.HasOne("CrmCorner.Models.AppUser", "AppUser")
                        .WithMany("Customers")
                        .HasForeignKey("AppUserId");

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("CrmCorner.Models.Feedback", b =>
                {
                    b.HasOne("CrmCorner.Models.SocialMediaContent", "SocialMediaContent")
                        .WithMany("Feedbacks")
                        .HasForeignKey("SocialMediaContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SocialMediaContent");
                });

            modelBuilder.Entity("CrmCorner.Models.FileAttachment", b =>
                {
                    b.HasOne("CrmCorner.Models.TaskComp", "Task")
                        .WithMany("FileAttachments")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");
                });

            modelBuilder.Entity("CrmCorner.Models.Notification", b =>
                {
                    b.HasOne("CrmCorner.Models.AppUser", "AppUser")
                        .WithMany("Notifications")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CrmCorner.Models.TaskComp", "TaskComp")
                        .WithOne("Notification")
                        .HasForeignKey("CrmCorner.Models.Notification", "TaskCompId");

                    b.Navigation("AppUser");

                    b.Navigation("TaskComp");
                });

            modelBuilder.Entity("CrmCorner.Models.PersonalBrandingContent", b =>
                {
                    b.HasOne("CrmCorner.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId");

                    b.HasOne("CrmCorner.Models.AppUser", "PersonalUser")
                        .WithMany()
                        .HasForeignKey("PersonalUserId");

                    b.Navigation("Company");

                    b.Navigation("PersonalUser");
                });

            modelBuilder.Entity("CrmCorner.Models.PersonalBrandingFeedback", b =>
                {
                    b.HasOne("CrmCorner.Models.AppUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("CrmCorner.Models.PersonalBrandingContent", "PersonalBrandingContent")
                        .WithMany("Feedbacks")
                        .HasForeignKey("PersonalBrandingContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("PersonalBrandingContent");
                });

            modelBuilder.Entity("CrmCorner.Models.PipelineTask", b =>
                {
                    b.HasOne("CrmCorner.Models.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CrmCorner.Models.CustomerN", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId");

                    b.HasOne("CrmCorner.Models.AppUser", "ResponsibleUser")
                        .WithMany()
                        .HasForeignKey("ResponsibleUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AppUser");

                    b.Navigation("Customer");

                    b.Navigation("ResponsibleUser");
                });

            modelBuilder.Entity("CrmCorner.Models.PipelineTaskFileAttachment", b =>
                {
                    b.HasOne("CrmCorner.Models.PipelineTask", "PipelineTask")
                        .WithMany("FileAttachments")
                        .HasForeignKey("PipelineTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PipelineTask");
                });

            modelBuilder.Entity("CrmCorner.Models.PipelineTaskHistory", b =>
                {
                    b.HasOne("CrmCorner.Models.PipelineTask", "PipelineTask")
                        .WithMany()
                        .HasForeignKey("PipelineTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PipelineTask");
                });

            modelBuilder.Entity("CrmCorner.Models.PipelineTaskLog", b =>
                {
                    b.HasOne("CrmCorner.Models.PipelineTask", "PipelineTask")
                        .WithMany()
                        .HasForeignKey("PipelineTaskId");

                    b.HasOne("CrmCorner.Models.AppUser", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById");

                    b.Navigation("PipelineTask");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("CrmCorner.Models.PipelineTaskNote", b =>
                {
                    b.HasOne("CrmCorner.Models.PipelineTask", "PipelineTask")
                        .WithMany("Notes")
                        .HasForeignKey("PipelineTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PipelineTask");
                });

            modelBuilder.Entity("CrmCorner.Models.PostSaleInfo", b =>
                {
                    b.HasOne("CrmCorner.Models.PipelineTask", "PipelineTask")
                        .WithOne("PostSaleInfo")
                        .HasForeignKey("CrmCorner.Models.PostSaleInfo", "PipelineTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PipelineTask");
                });

            modelBuilder.Entity("CrmCorner.Models.SocialMediaContent", b =>
                {
                    b.HasOne("CrmCorner.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("CrmCorner.Models.TableHeader", b =>
                {
                    b.HasOne("CrmCorner.Models.Company", "Company")
                        .WithMany("TableHeaders")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Company");
                });

            modelBuilder.Entity("CrmCorner.Models.TaskComp", b =>
                {
                    b.HasOne("CrmCorner.Models.AppUser", "AssignedUser")
                        .WithMany()
                        .HasForeignKey("AssignedUserId");

                    b.HasOne("CrmCorner.Models.CustomerN", "Customer")
                        .WithMany("Taskcomps")
                        .HasForeignKey("CustomerId");

                    b.HasOne("CrmCorner.Models.Status", "Status")
                        .WithMany("TaskComps")
                        .HasForeignKey("StatusId");

                    b.HasOne("CrmCorner.Models.AppUser", "AppUser")
                        .WithMany("TaskComps")
                        .HasForeignKey("UserId");

                    b.Navigation("AppUser");

                    b.Navigation("AssignedUser");

                    b.Navigation("Customer");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("CrmCorner.Models.TaskCompLog", b =>
                {
                    b.HasOne("CrmCorner.Models.TaskComp", "Task")
                        .WithMany("TaskCompLogs")
                        .HasForeignKey("TaskId");

                    b.HasOne("CrmCorner.Models.AppUser", "UpdatedBy")
                        .WithMany("TaskCompLogs")
                        .HasForeignKey("UpdatedById");

                    b.Navigation("Task");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("CrmCorner.Models.TaskCompNote", b =>
                {
                    b.HasOne("CrmCorner.Models.TaskComp", "TaskComp")
                        .WithMany("Notes")
                        .HasForeignKey("TaskCompId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaskComp");
                });

            modelBuilder.Entity("CrmCorner.Models.ToDo", b =>
                {
                    b.HasOne("CrmCorner.Models.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AppUserId");

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("CrmCorner.Models.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("CrmCorner.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("CrmCorner.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("CrmCorner.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CrmCorner.Models.AppRole", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("CrmCorner.Models.AppUser", b =>
                {
                    b.Navigation("Calendars");

                    b.Navigation("Customers");

                    b.Navigation("Notifications");

                    b.Navigation("TaskCompLogs");

                    b.Navigation("TaskComps");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("CrmCorner.Models.Company", b =>
                {
                    b.Navigation("TableHeaders");
                });

            modelBuilder.Entity("CrmCorner.Models.CustomerN", b =>
                {
                    b.Navigation("Taskcomps");
                });

            modelBuilder.Entity("CrmCorner.Models.PersonalBrandingContent", b =>
                {
                    b.Navigation("Feedbacks");
                });

            modelBuilder.Entity("CrmCorner.Models.PipelineTask", b =>
                {
                    b.Navigation("FileAttachments");

                    b.Navigation("Notes");

                    b.Navigation("PostSaleInfo");
                });

            modelBuilder.Entity("CrmCorner.Models.SocialMediaContent", b =>
                {
                    b.Navigation("Feedbacks");
                });

            modelBuilder.Entity("CrmCorner.Models.Status", b =>
                {
                    b.Navigation("TaskComps");
                });

            modelBuilder.Entity("CrmCorner.Models.TaskComp", b =>
                {
                    b.Navigation("FileAttachments");

                    b.Navigation("Notes");

                    b.Navigation("Notification");

                    b.Navigation("TaskCompLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
