// <auto-generated />
using System;
using CrmCorner.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CrmCorner.Migrations
{
    [DbContext(typeof(CrmCornerContext))]
    [Migration("20250708002239_RemoveIdentityUserRoleInheritance")]
    partial class RemoveIdentityUserRoleInheritance
    {
        /// <inheritdoc />
 
    }
}
